version: '3.8'

services:
  solana-moon-dashboard:
    build: .
    container_name: solana-moon-dashboard
    ports:
      - "9000:9000"
    volumes:
      - ./src:/app/src
      - ./webpack.config.js:/app/webpack.config.js
      - /app/node_modules
    environment:
      - NODE_ENV=development
      - CHOKIDAR_USEPOLLING=true
    restart: unless-stopped
    networks:
      - solana-network

  nginx:
    image: nginx:alpine
    container_name: solana-nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./ssl:/etc/nginx/ssl:ro
    depends_on:
      - solana-moon-dashboard
    restart: unless-stopped
    networks:
      - solana-network
    profiles:
      - production

networks:
  solana-network:
    driver: bridge

volumes:
  node_modules:
